freebsd-relayd: relayd: Add a missing string.h header to siphash.c
This change fixes the following error:

```
siphash.c:78:2: error: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        memset(ctx->buf, 0, sizeof(ctx->buf));
```